---@class KeyManager
---@A table that stores event listeners by mode ("UP" or "DOWN").
KeyManager = {}

--- Adds an event listener for key events.
---@param func function @The function to execute when the event is triggered.
---@param inMode '"UP"'|'"DOWN"' @Specifies the event type: "UP" for key release, "DOWN" for key press.
function KeyManager.addEventListener(func, inMode) end

--- Removes an event listener for key events.
---@param func function @The function that was previously added as a listener.
---@---@param inMode '"UP"'|'"DOWN"' @Specifies the event type: "UP" for key release, "DOWN" for key press.
function KeyManager.removeEventListener(func, inMode) end

Key = {
    UNKNOWN = nil,
    A = nil,
    B = nil,
    C = nil,
    D = nil,
    E = nil,
    F = nil,
    G = nil,
    H = nil,
    I = nil,
    J = nil,
    K = nil,
    L = nil,
    M = nil,
    N = nil,
    O = nil,
    P = nil,
    Q = nil,
    R = nil,
    S = nil,
    T = nil,
    U = nil,
    V = nil,
    W = nil,
    X = nil,
    Y = nil,
    Z = nil,
    ["1"] = nil,
    ["2"] = nil,
    ["3"] = nil,
    ["4"] = nil,
    ["5"] = nil,
    ["6"] = nil,
    ["7"] = nil,
    ["8"] = nil,
    ["9"] = nil,
    ["0"] = nil,
    RETURN = nil,
    ESCAPE = nil,
    BACKSPACE = nil,
    TAB = nil,
    SPACE = nil,
    MINUS = nil,
    EQUALS = nil,
    LEFTBRACKET = nil,
    RIGHTBRACKET = nil,
    BACKSLASH = nil,
    SEMICOLON = nil,
    QUOTE = nil,
    COMMA = nil,
    PERIOD = nil,
    SLASH = nil,
    CAPSLOCK = nil,
    F1 = nil,
    F2 = nil,
    F3 = nil,
    F4 = nil,
    F5 = nil,
    F6 = nil,
    F7 = nil,
    F8 = nil,
    F9 = nil,
    F10 = nil,
    F11 = nil,
    F12 = nil,
    PRINTSCREEN = nil,
    SCROLLLOCK = nil,
    PAUSE = nil,
    INSERT = nil,
    HOME = nil,
    PAGEUP = nil,
    DELETE = nil,
    END = nil,
    PAGEDOWN = nil,
    RIGHT = nil,
    LEFT = nil,
    DOWN = nil,
    UP = nil
}
